// ./src/app/contact/metadata.js

export const metadata = {
  title: "Gorakhpur Website Wala",
  description: "Welcome to Gorakhpur Website Wala! We specialize in website development, app development, website maintenance, SEO, digital marketing, marketing consultation, domain hosting, and e-commerce services in Gorakhpur, Pipiganj, and across Uttar Pradesh.",
  keywords: [
    "Website development in Gorakhpur",
    "App development in Gorakhpur",
    "Website maintenance in Gorakhpur",
    "SEO in Gorakhpur",
    "Digital marketing in Gorakhpur",
    "Marketing consultation in Gorakhpur",
    "Domain hosting in Gorakhpur",
    "E-commerce solutions in Gorakhpur",
    "Best website developers in Gorakhpur",
    "Web design company in Gorakhpur",
    "Web development company in Gorakhpur",
    "Digital marketing agency in Gorakhpur",
    "Website development in Peppeganj",
    "App development in Peppeganj",
    "Website maintenance in Peppeganj",
    "SEO services in Peppeganj",
    "Digital marketing in Peppeganj",
    "Marketing consultation in Peppeganj",
    "Domain hosting in Peppeganj",
    "E-commerce solutions in Peppeganj",
    "Best website developers in Peppeganj",
    "Web design company in Peppeganj",
    "Web development company in Peppeganj",
    "Digital marketing agency in Peppeganj",
    "Website development in Pipiganj",
    "App development in Pipiganj",
    "Website maintenance in Pipiganj",
    "SEO services in Pipiganj",
    "Digital marketing in Pipiganj",
    "Marketing consultation in Pipiganj",
    "Domain hosting in Pipiganj",
    "E-commerce solutions in Pipiganj",
    "Best website developers in Pipiganj",
    "Web design company in Pipiganj",
    "Web development company in Pipiganj",
    "Digital marketing agency in Pipiganj",
    "Website development in Uttar Pradesh",
    "App development in Uttar Pradesh",
    "Website maintenance in Uttar Pradesh",
    "SEO services in Uttar Pradesh",
    "Digital marketing in Uttar Pradesh",
    "Marketing consultation in Uttar Pradesh",
    "Domain hosting in Uttar Pradesh",
    "E-commerce solutions in Uttar Pradesh",
    "Best website developers in Uttar Pradesh",
    "Web design company in Uttar Pradesh",
    "Web development company in Uttar Pradesh",
    "Digital marketing agency in Uttar Pradesh",
    "Websitewala in Gorakhpur",
    "Websitewala in Uttar Pradesh",
    "Website development company",
    "Web development company",
    "Web design company",
    "Web development services",
    "Best website developers",
    "Website developer",
    "Website design and development",
    "Website developers",
    "Website design websites",
    "Gorakhpur Website Wala",
  ]  
};
